//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabianCo.Localization.SourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArabianCo.Localization.SourceFiles.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute data type does not match input.
        /// </summary>
        
        /// <summary>
        ///   Looks up a localized string similar to Cant be deactivate It has related {0}.
        /// </summary>
        public static string ObjectCantBeDeactivate {
            get {
                return ResourceManager.GetString("ObjectCantBeDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant be delete it has related {0}.
        /// </summary>
        public static string ObjectCantBeDelete {
            get {
                return ResourceManager.GetString("ObjectCantBeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Is Already Exist.
        /// </summary>
        public static string ObjectIsAlreadyExist {
            get {
                return ResourceManager.GetString("ObjectIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Not Found.
        /// </summary>
        public static string ObjectWasNotFound {
            get {
                return ResourceManager.GetString("ObjectWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number allowed..
        /// </summary>
        
        /// <summary>
        ///   Looks up a localized string similar to Your signingup information not correct.
        /// </summary>
        public static string SignUpNotComplete {
            get {
                return ResourceManager.GetString("SignUpNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Position Is Already Exist.
        /// </summary>

        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is expired..
        /// </summary>
        public static string VerificationCodeIsExpired {
            get {
                return ResourceManager.GetString("VerificationCodeIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code isn&apos;t correct.
        /// </summary>
        public static string VerificationCodeIsnotCorrect {
            get {
                return ResourceManager.GetString("VerificationCodeIsnotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code Isn&apos;t valid.
        /// </summary>
        public static string VerificationCodeIsnotValid {
            get {
                return ResourceManager.GetString("VerificationCodeIsnotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t not do this action.
        /// </summary>
        public static string YouCannotDoThisAction {
            get {
                return ResourceManager.GetString("YouCannotDoThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number is not verified.
        /// </summary>
        public static string YourPhoneNumberIsntVerified {
            get {
                return ResourceManager.GetString("YourPhoneNumberIsntVerified", resourceCulture);
            }
        }
    }
}
